app/models.py
import mindsdb_sdk
import os

def create_models():
    server = mindsdb_sdk.connect()
    project = server.get_project("ai_blog_bot")

    try:
        server.ml_engines.create(
            name="minds_endpoint_engine",
            type="minds_endpoint",
            connection_data={"minds_endpoint_api_key": os.getenv("API_KEY")}
        )
    except Exception as e:
        print(f"ML Engine creation failed: {e}")

    try:
        project = server.create_project("ai_blog_bot")
    except Exception as e:
        project = server.get_project("ai_blog_bot")

    try:
        project.models.create(
            name="blog_generator_title",
            predict="blog_content",
            engine="minds_endpoint_engine",
            max_tokens=152,
            prompt_template="Write a Blog Post Title about {{topic}} in about 50 words."
        )
    except Exception as e:
        print(f"Model creation failed: {e}")

    try:
        project.models.create(
            name="blog_generator_intro",
            predict="blog_introduction",
            engine="minds_endpoint_engine",
            max_tokens=500,
            prompt_template="Write only the intro part for my blogpost regarding the topic {{topic}}.Do not generate the whole blog post, just the introduction part of it. The introduction should be around 50 words.Do not Write Introduction word in it."
        )
    except Exception as e:
        print(f"Model creation failed: {e}")

    try:
        project.models.create(
            name="blog_generator_body",
            predict="blog_body",
            engine="minds_endpoint_engine",
            max_tokens=2048,
            prompt_template="Write the Body of the Blog Post about {{topic}} and the body should be 300 words.Do it in a way that it should be a continuation of the introduction. Do not Write Body word in it.Also give in paragraph format.Dont include the conclusion part in it."
        )
    except Exception as e:
        print(f"Model creation failed: {e}")

    try:
        project.models.create(
            name="blog_generator_conclusion",
            predict="blog_conclusion",
            engine="minds_endpoint_engine",
            max_tokens=152,
            prompt_template="Write a Blog Post Conclusion about {{topic}}.Do not generate other parts of the blog post, just the conclusion part of it. The conclusion should be around 50 words. Do not Write Conclusion word in it."
        )
    except Exception as e:
        print(f"Model creation failed: {e}")

    return project

main.py
from flask import Flask, render_template
from routes import routes

app = Flask(__name__)
app.register_blueprint(routes, url_prefix="")

if __name__ == "__main__":
    app.run(debug=True)

routes.py
from flask import Blueprint, render_template, request, send_file
import os
from app.generate_pdf import generate_pdf
from app.generate_img import generate_image
from app.models import create_models
from dotenv import load_dotenv

routes = Blueprint("routes", __name__, template_folder="templates", static_folder="static")

load_dotenv()

@routes.route('/')
def index():
    return render_template('index.html')

@routes.route('/generate', methods=['POST'])
def generate_blog():
    project = create_models()
    topic = request.form['topic']

    model = project.models.get("blog_generator_title")
    model_intro = project.models.get("blog_generator_intro")
    model_body = project.models.get("blog_generator_body")
    model_conclusion = project.models.get("blog_generator_conclusion")

    result_intro = model_intro.predict({"topic": topic})
    result = model.predict({"topic": topic})
    result_body = model_body.predict({"topic": topic})
    result_conclusion = model_conclusion.predict({"topic": topic})
    
    blog_intro = result_intro['blog_introduction'][0]
    blog_title = result['blog_content'][0]
    blog_body = result_body['blog_body'][0]
    blog_conclusion = result_conclusion['blog_conclusion'][0]

    image_url = generate_image(f"{topic} blog post illustration")

    pdf_filename = generate_pdf(blog_title, blog_intro, blog_body, blog_conclusion,image_url)
    
    return render_template('blog.html', topic=topic, title=blog_title,intro=blog_intro,body=blog_body,conclusion=blog_conclusion,image_url=image_url ,pdf_filename=pdf_filename,pdf_ready=True)

@routes.route('/download/<filename>', methods=['GET'])
def download(filename):
    file_path = os.path.join(routes.root_path, filename)
    return send_file(file_path, as_attachment=True)

templates/blog.html
<!DOCTYPE html>
<html>

<head>
  <title>Blog Post</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='blog.css') }}">
</head>

<body>
  <div class="container">
    <div class="main">
      <div class="title">
        <h1>{{ title }}</h1>
      </div>
      <div class="intro">
        <h2>Introduction</h2>
        <pre>{{ intro }}</pre>
      </div>
      <div class="body">
        <h2>Body</h2>
        <pre>{{ body }}</pre>
        {% if image_url %}
        <img src="{{ image_url }}" alt="Blog Post Image">
        {% endif %}
      </div>
      <div class="conclusion">
        <h2>Conclusion</h2>
        <pre>{{ conclusion }}</pre>
      </div>
    </div>
    <div class="buttons">
      <div class="generate-another beautiful-button">
        <a href="/">Generate Another</a>
      </div>
      {% if pdf_ready %}
      <form action="{{ url_for('routes.download', filename=pdf_filename) }}" method="get">
        <button type="submit" class="generate-another beautiful-button">Download PDF</button>
      </form>
      {% endif %}
    </div>
  </div>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html>

<head>
  <title>Blog Generator</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>

<body>
  <div class="header" id="header">
    <h1>AI-Blog Writer</h1>
    <h2>Transform Ideas into Blog Posts Instantly</h2>
  </div>
  <form id="blogForm" action="/generate" method="post" onsubmit="showLoader()">
    <div class="group">
      <svg viewBox="0 0 24 24" aria-hidden="true" class="search-icon">
        <g>
          <path
            d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z">
          </path>
        </g>
      </svg>

      <input id="query topic" class="input" type="text" placeholder="Topic..." name="topic" required />
    </div>
    <button type="submit">
      Generate
      <div class="star-1">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1"
          style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
          viewBox="0 0 784.11 815.53" xmlns:xlink="http://www.w3.org/1999/xlink">
          <defs></defs>
          <g id="Layer_x0020_1">
            <metadata id="CorelCorpID_0Corel-Layer"></metadata>
            <path class="fil0"
              d="M392.05 0c-20.9,210.08 -184.06,378.41 -392.05,407.78 207.96,29.37 371.12,197.68 392.05,407.74 20.93,-210.06 184.09,-378.37 392.05,-407.74 -207.98,-29.38 -371.16,-197.69 -392.06,-407.78z">
            </path>
          </g>
        </svg>
      </div>
      <div class="star-2">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1"
          style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
          viewBox="0 0 784.11 815.53" xmlns:xlink="http://www.w3.org/1999/xlink">
          <defs></defs>
          <g id="Layer_x0020_1">
            <metadata id="CorelCorpID_0Corel-Layer"></metadata>
            <path class="fil0"
              d="M392.05 0c-20.9,210.08 -184.06,378.41 -392.05,407.78 207.96,29.37 371.12,197.68 392.05,407.74 20.93,-210.06 184.09,-378.37 392.05,-407.74 -207.98,-29.38 -371.16,-197.69 -392.06,-407.78z">
            </path>
          </g>
        </svg>
      </div>
      <div class="star-3">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1"
          style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
          viewBox="0 0 784.11 815.53" xmlns:xlink="http://www.w3.org/1999/xlink">
          <defs></defs>
          <g id="Layer_x0020_1">
            <metadata id="CorelCorpID_0Corel-Layer"></metadata>
            <path class="fil0"
              d="M392.05 0c-20.9,210.08 -184.06,378.41 -392.05,407.78 207.96,29.37 371.12,197.68 392.05,407.74 20.93,-210.06 184.09,-378.37 392.05,-407.74 -207.98,-29.38 -371.16,-197.69 -392.06,-407.78z">
            </path>
          </g>
        </svg>
      </div>
      <div class="star-4">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1"
          style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
          viewBox="0 0 784.11 815.53" xmlns:xlink="http://www.w3.org/1999/xlink">
          <defs></defs>
          <g id="Layer_x0020_1">
            <metadata id="CorelCorpID_0Corel-Layer"></metadata>
            <path class="fil0"
              d="M392.05 0c-20.9,210.08 -184.06,378.41 -392.05,407.78 207.96,29.37 371.12,197.68 392.05,407.74 20.93,-210.06 184.09,-378.37 392.05,-407.74 -207.98,-29.38 -371.16,-197.69 -392.06,-407.78z">
            </path>
          </g>
        </svg>
      </div>
      <div class="star-5">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1"
          style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
          viewBox="0 0 784.11 815.53" xmlns:xlink="http://www.w3.org/1999/xlink">
          <defs></defs>
          <g id="Layer_x0020_1">
            <metadata id="CorelCorpID_0Corel-Layer"></metadata>
            <path class="fil0"
              d="M392.05 0c-20.9,210.08 -184.06,378.41 -392.05,407.78 207.96,29.37 371.12,197.68 392.05,407.74 20.93,-210.06 184.09,-378.37 392.05,-407.74 -207.98,-29.38 -371.16,-197.69 -392.06,-407.78z">
            </path>
          </g>
        </svg>
      </div>
      <div class="star-6">
        <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" version="1.1"
          style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
          viewBox="0 0 784.11 815.53" xmlns:xlink="http://www.w3.org/1999/xlink">
          <defs></defs>
          <g id="Layer_x0020_1">
            <metadata id="CorelCorpID_0Corel-Layer"></metadata>
            <path class="fil0"
              d="M392.05 0c-20.9,210.08 -184.06,378.41 -392.05,407.78 207.96,29.37 371.12,197.68 392.05,407.74 20.93,-210.06 184.09,-378.37 392.05,-407.74 -207.98,-29.38 -371.16,-197.69 -392.06,-407.78z">
            </path>
          </g>
        </svg>
      </div>
    </button>

  </form>
  <div class="loader" id="loader">
    <div class="cell d-0"></div>
    <div class="cell d-1"></div>
    <div class="cell d-2"></div>
    <div class="cell d-1"></div>
    <div class="cell d-2"></div>
    <div class="cell d-2"></div>
    <div class="cell d-3"></div>
    <div class="cell d-3"></div>
    <div class="cell d-4"></div>
  </div>

  <script>
    function showLoader() {
      var blogForm = document.getElementById('blogForm');
      var header = document.getElementById('header');
      var loader = document.getElementById('loader');
      loader.style.display = 'flex';
      blogForm.classList.add('blur');
      header.classList.add('blur');
      setTimeout(function () {
        blogForm.classList.remove('blur');
        header.classList.remove('blur');
        loader.style.display = 'none';
      }, 33000);
    }
  </script>
</body>

</html>